### ISSUE TITLE
How to open a modal on another modal?

### ISSUE THREAD

**Issue by phirum** [PeppeL-G/bootstrap-3-modal#8] opened 2015-01-28 04:48 UTC
Hello, thank you for your package.

But I have one question:
Is it possible if I want to open a modal on another modal?
For example I opened a modal that has "a button" and when I click on this button I want to show another modal without closing the first one.

Thank you in advance.

**Comment by PeppeL-G** [comment] 2015-01-28 15:30
Duplicate of issue #7.

**Closed as completed by PeppeL-G** 2015-01-28 15:30 UTC
