### ISSUE TITLE
plan for multiple level support?

### ISSUE THREAD

**Issue by thearabbit** [PeppeL-G/bootstrap-3-modal#9] opened 2015-01-28 08:04 UTC
when I check your code, and comment on:

```
        // Only show the modal if no modal is shown at the moment.
        // See issue #2.
        //if($modal == null){

        var template = Template.peppelg_modal_test;
        var data = {
            templateName: templateName,
            data: data
        };
        var parentNode = document.body;

        view = Blaze.renderWithData(template, data, parentNode);

        //}
```

it is OK for modal on modal, but i know the problem when click more then one time (duplicate modal).
have any solutions?

**Comment by PeppeL-G** [comment] 2015-01-28 15:31
Duplicate of issue #7.

**Closed as completed by PeppeL-G** 2015-01-28 15:31 UTC

**Comment by thearabbit** [comment] 2015-01-29 02:02
Sorry,
